### ISSUE TITLE
ValueError: zero-size array to reduction operation minimum which has no identity

### ISSUE THREAD

**Issue by edisonchensy** [edisonchensy/ValueError-zero-size-array-to-reduction-operation-minimum-which-has-no-identity#1]
The following is the error I got and the very bottom part is the function that relates to the error (rendering/utils.py). 

edison@amax:~/ssd-6d-master$ python3 run.py -d /home/edison/edison/ssd-6d-master/datasets/test/ -n /home/edison/edison/ssd-6d-master/models/hinterstoisser_obj_01.pb
/home/edison/anaconda3/lib/python3.6/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
2018-04-06 15:41:26.831824: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
Loading obj_01.ply with vertex colors
Models: ['obj_01']
Views: 337
Inplanes: 18
Priors: (21222, 8)
Precomputing projections for each used model...
  0%|                                                                                                                                                                  | 0/337 [00:00<?, ?it/s]
Traceback (most recent call last):
  File "run.py", line 76, in <module>
    m.projections = precompute_projections(views, inplanes, bench.cam, m)
  File "/home/edison/ssd-6d-master/rendering/utils.py", line 118, in precompute_projections
    box = [box.min(0)[1], box.min(0)[0], box.max(0)[1] + 1, box.max(0)[0] + 1]
  File "/home/edison/anaconda3/lib/python3.6/site-packages/numpy/core/_methods.py", line 29, in _amin
    return umr_minimum(a, axis, None, out, keepdims)
ValueError: zero-size array to reduction operation minimum which has no identity

def precompute_projections(views, inplanes, cam, model3D):
    """Precomputes the projection information needed for 6D pose construction

    # Arguments
        views: List of 3D viewpoint positions
        inplanes: List of inplane angles in degrees
        cam: Intrinsics to use for translation estimation
        model3D: Model3D instance

    # Returns
        data: a 3D list with precomputed entities with shape
            (views, inplanes, (4x4 pose matrix, 3) )
    """
    w, h = 640, 480
    ren = Renderer((w, h), cam)
    data = []
    if model3D.vertices is None:
        return data

    for v in tqdm(range(len(views))):
        data.append([])
        for i in inplanes:
            pose = create_pose(views[v], angle_deg=i)
            pose[:3, 3] = [0, 0, 0.5]  # zr = 0.5

            # Render object and extract tight 2D bbox and projected 2D centroid
            ren.clear()
            ren.draw_model(model3D, pose)
            box = np.argwhere(ren.finish()[1])  # Deduct bbox from depth rendering
            
            box = [box.min(0)[1], box.min(0)[0], box.max(0)[1] + 1, box.max(0)[0] + 1]
   
            centroid = np.matmul(pose[:3, :3], model3D.centroid) + pose[:3, 3]
            centroid_x = cam[0, 2] + centroid[0] * cam[0, 0] / centroid[2]
            centroid_y = cam[1, 2] + centroid[1] * cam[1, 1] / centroid[2]

            # Compute 2D centroid position in normalized, box-local reference frame
            box_w, box_h = (box[2] - box[0]), (box[3] - box[1])
            norm_centroid_x = (centroid_x - box[0]) / box_w
            norm_centroid_y = (centroid_y - box[1]) / box_h

            # Compute normalized diagonal box length
            lr = np.sqrt((box_w / w) ** 2 + (box_h / h) ** 2)
            data[-1].append((pose, [norm_centroid_x, norm_centroid_y, lr]))
    return data

thanks

**Comment by Qiiiiiiiiii** [comment]
@edisonchensy I have solved that error about 'pyglet' and get the same error about valueError. Have you solve it? Thanks!

**Comment by edisonchensy** [comment]
I haven’t solved valueError problem, could you please give me a help? I print the box, it’s ［］and its shape is (0,2). This valueError problem really confuses me :(




| |
EDC
邮箱：shandianball@126.com
|

签名由 网易邮箱大师 定制

On 04/11/2018 19:40, Qiiiiiiiiii wrote:

@edisonchensy I have solved that error about 'pyglet' and get the same error about valueError. Have you solve it? Thanks!

**Comment by Qiiiiiiiiii** [comment]
@edisonchensy You use NetEase mail?

**Comment by Qiiiiiiiiii** [comment]
@edisonchensy It seems that you are studying in SJTU. And is it convenient for you to provide your QQ/Wechat for communication?

**Comment by edisonchensy** [comment]
Hi, have you solved the valueError problem? I still don’t get it. If u solved, could you give me a help? Thanks





| |
EDC
邮箱：shandianball@126.com
|

签名由 网易邮箱大师 定制

On 04/11/2018 19:46, edisonchensy wrote:
I haven’t solved valueError problem, could you please give me a help? I print the box, it’s ［］and its shape is (0,2). This valueError problem really confuses me :(




| |
EDC
邮箱：shandianball@126.com
|

签名由 网易邮箱大师 定制

On 04/11/2018 19:40, Qiiiiiiiiii wrote:

@edisonchensy I have solved that error about 'pyglet' and get the same error about valueError. Have you solve it? Thanks!
